import { notFound } from "next/navigation";
import { hashAccessToken } from "@/lib/access";
import { prisma } from "@/lib/prisma";
import { addClientComment, completeClientAction } from "./actions";

export const dynamic = "force-dynamic";

export default async function ClientProject({ params, searchParams }: { params: Promise<{key:string}>; searchParams: Promise<{token?:string}> }) {
  const [{key},{token}] = await Promise.all([params,searchParams]); if (!token) notFound();
  const project = await prisma.project.findFirst({ where:{ key, accessTokens:{some:{tokenHash:hashAccessToken(token),revokedAt:null,expiresAt:{gt:new Date()}}}}, include:{client:true,tasks:{where:{visibleToClient:true},orderBy:{sortOrder:"asc"}},milestones:{orderBy:{sortOrder:"asc"}},clientActions:{where:{status:"OPEN"},orderBy:{createdAt:"desc"}},comments:{where:{visibleToClient:true},orderBy:{createdAt:"desc"},take:20},attachments:{where:{visibleToClient:true},orderBy:{createdAt:"desc"},take:12},events:{orderBy:{createdAt:"desc"},take:8}} });
  if (!project) notFound();
  const services = project.selectedServices as Array<{id:string;name:string;quantity:number}>; const completed = project.tasks.filter(task=>task.status === "DONE").length; const progress = project.tasks.length ? Math.round(completed/project.tasks.length*100) : 0;
  return <main className="portal"><div className="row"><div className="brand">NECROTIX / WORKSPACE</div><span className="badge">{project.status.replaceAll("_"," ")}</span></div><section className="portal-head"><span className="eyebrow">{project.reference} / {project.client.name}</span><h1>{project.title}</h1><p className="lead">{project.description ?? "Your project scope, progress and next actions in one place."}</p></section>
    <div className="metrics"><div className="card metric"><span className="muted">Progress</span><strong>{progress}%</strong></div><div className="card metric"><span className="muted">Tasks</span><strong>{project.tasks.length}</strong></div><div className="card metric"><span className="muted">Completed</span><strong>{completed}</strong></div><div className="card metric"><span className="muted">Last update</span><strong className="date-value">{project.updatedAt.toLocaleDateString()}</strong></div></div>
    {project.clientActions.length > 0 && <section className="attention"><div><span className="eyebrow">Waiting for you</span><h2>Your input keeps the project moving.</h2></div>{project.clientActions.map(action=><article className="action-card" key={action.id}><div><b>{action.title}</b>{action.description && <p>{action.description}</p>}</div><form action={completeClientAction}><input type="hidden" name="key" value={key}/><input type="hidden" name="token" value={token}/><input type="hidden" name="actionId" value={action.id}/><button className="button acid">Mark completed</button></form></article>)}</section>}
    <section className="workspace"><div className="card"><div className="section-title">Project tasks</div>{project.tasks.map(task=><article className="project" key={task.id}><div><h3>{task.title}</h3><span className="muted">{task.description}</span></div><span className="badge">{task.status.replaceAll("_"," ")}</span></article>)}</div><div className="card"><div className="section-title">Milestones</div>{project.milestones.length ? project.milestones.map(item=><div className="compact-row" key={item.id}><b>{item.title}</b><span className="badge">{item.status}</span></div>) : <p className="empty">Milestones will appear when delivery planning begins.</p>}<div className="section-title spaced">Selected services</div><div className="services single">{services.map(service=><div className="service" key={service.id}><b>{service.name}</b><div className="muted">Quantity {service.quantity}</div></div>)}</div></div></section>
    <section className="detail-grid client-details"><div className="card"><div className="section-title">Conversation</div>{project.comments.map(comment=><div className="message" key={comment.id}><div className="row"><b>{comment.authorName}</b><span className="muted">{comment.createdAt.toLocaleString()}</span></div><p>{comment.body}</p></div>)}<form className="stack-form" action={addClientComment}><input type="hidden" name="key" value={key}/><input type="hidden" name="token" value={token}/><textarea name="body" required maxLength={5000} placeholder="Write a comment or question"/><button className="button">Send comment</button></form></div><div className="card"><div className="section-title">Files</div>{project.attachments.length ? project.attachments.map(file=><div className="compact-row" key={file.id}><b>{file.fileName}</b><span className="muted">v{file.version}</span></div>) : <p className="empty">No shared files yet.</p>}<div className="section-title spaced">Latest activity</div><ul className="activity">{project.events.map(event=><li key={event.id}><b>{event.message}</b><br/><span className="muted">{event.createdAt.toLocaleString()}</span></li>)}</ul></div></section>
  </main>;
}
