import Link from "next/link";
import { notFound } from "next/navigation";
import { TaskStatus } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { createClientAction, createComment, createMilestone, moveTask } from "./actions";

export const dynamic = "force-dynamic";
const columns: Array<{ status: TaskStatus; label: string }> = [{ status: "BACKLOG", label: "Backlog" }, { status: "READY", label: "Ready" }, { status: "IN_PROGRESS", label: "In progress" }, { status: "REVIEW", label: "Review" }, { status: "DONE", label: "Done" }];

export default async function ProjectWorkspace({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const project = await prisma.project.findUnique({ where: { id }, include: { client: true, tasks: { orderBy: { sortOrder: "asc" } }, milestones: { orderBy: { sortOrder: "asc" } }, clientActions: { orderBy: { createdAt: "desc" } }, comments: { orderBy: { createdAt: "desc" }, take: 20 }, attachments: { orderBy: { createdAt: "desc" }, take: 12 }, events: { orderBy: { createdAt: "desc" }, take: 12 } } });
  if (!project) notFound();
  const completed = project.tasks.filter(task => task.status === "DONE").length;
  const progress = project.tasks.length ? Math.round(completed / project.tasks.length * 100) : 0;
  return <main className="project-page"><header className="topbar"><Link className="back" href="/dashboard">← Dashboard</Link><span className="badge">{project.status.replaceAll("_", " ")}</span></header>
    <section className="project-hero"><span className="eyebrow">{project.reference} / {project.client.name}</span><h1>{project.title}</h1><p className="lead">{project.description ?? "Project delivery workspace"}</p><div className="progress large"><span style={{ width: `${progress}%` }}/></div><span className="muted">{progress}% complete · {completed}/{project.tasks.length} tasks</span></section>
    <section className="board" aria-label="Project task board">{columns.map(column => <div className="board-column" key={column.status}><div className="row"><div className="section-title">{column.label}</div><span className="count">{project.tasks.filter(task=>task.status === column.status).length}</span></div>{project.tasks.filter(task=>task.status === column.status).map(task => <article className="task-card" key={task.id}><b>{task.title}</b>{task.description && <p className="muted">{task.description}</p>}<form action={moveTask}><input type="hidden" name="taskId" value={task.id}/><input type="hidden" name="projectId" value={project.id}/><label className="sr-only" htmlFor={`status-${task.id}`}>Move task</label><select id={`status-${task.id}`} name="status" defaultValue={task.status}>{columns.map(option=><option value={option.status} key={option.status}>{option.label}</option>)}</select><button className="mini-button">Move</button></form></article>)}</div>)}</section>
    <section className="detail-grid"><div className="card"><div className="section-title">Milestones</div>{project.milestones.map(item=><div className="compact-row" key={item.id}><b>{item.title}</b><span className="badge">{item.status}</span></div>)}<form className="inline-form" action={createMilestone}><input type="hidden" name="projectId" value={project.id}/><input name="title" required maxLength={160} placeholder="New milestone"/><button className="button">Add</button></form></div>
      <div className="card"><div className="section-title">Waiting for client</div>{project.clientActions.filter(item=>item.status === "OPEN").map(item=><div className="compact-row stack" key={item.id}><b>{item.title}</b>{item.description && <span className="muted">{item.description}</span>}</div>)}<form className="stack-form" action={createClientAction}><input type="hidden" name="projectId" value={project.id}/><input name="title" required maxLength={180} placeholder="Action title"/><textarea name="description" maxLength={2000} placeholder="What does the client need to do?"/><button className="button">Request action</button></form></div>
      <div className="card"><div className="section-title">Comments and notes</div>{project.comments.map(comment=><div className="message" key={comment.id}><div className="row"><b>{comment.authorName}</b><span className="muted">{comment.visibleToClient ? "Client visible" : "Internal"}</span></div><p>{comment.body}</p></div>)}<form className="stack-form" action={createComment}><input type="hidden" name="projectId" value={project.id}/><textarea name="body" required maxLength={5000} placeholder="Add a project note"/><label className="check"><input type="checkbox" name="visibleToClient" defaultChecked/> Visible to client</label><button className="button">Add comment</button></form></div>
      <div className="card"><div className="section-title">Files</div>{project.attachments.length ? project.attachments.map(file=><div className="compact-row" key={file.id}><b>{file.fileName}</b><span className="muted">v{file.version}</span></div>) : <p className="empty">Storage adapter ready. No files uploaded.</p>}<div className="section-title spaced">Activity</div><ul className="activity">{project.events.map(event=><li key={event.id}><b>{event.message}</b><br/><span className="muted">{event.createdAt.toLocaleString()}</span></li>)}</ul></div></section>
  </main>;
}
