import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { applyProjectTemplate, createClientAction, createComment, createMilestone, importProjectFileFromUrl, reviewChangeRequest, uploadProjectFile } from "./actions";
import { TaskBoard } from "./task-board";

export const dynamic = "force-dynamic";
export default async function ProjectWorkspace({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const [project, templates] = await Promise.all([prisma.project.findUnique({ where: { id }, include: { client: true, tasks: { orderBy: { sortOrder: "asc" } }, milestones: { orderBy: { sortOrder: "asc" } }, clientActions: { orderBy: { createdAt: "desc" } }, comments: { orderBy: { createdAt: "desc" }, take: 20 }, attachments: { orderBy: { createdAt: "desc" }, take: 12 }, changeRequests: { orderBy: { createdAt: "desc" } }, events: { orderBy: { createdAt: "desc" }, take: 12 } } }), prisma.projectTemplate.findMany({ where: { active: true }, orderBy: { name: "asc" } })]);
  if (!project) notFound();
  const completed = project.tasks.filter(task => task.status === "DONE").length;
  const progress = project.tasks.length ? Math.round(completed / project.tasks.length * 100) : 0;
  return <main className="project-page"><header className="topbar"><Link className="back" href="/dashboard">← Dashboard</Link><span className="badge">{project.status.replaceAll("_", " ")}</span></header>
    <section className="project-hero"><span className="eyebrow">{project.reference} / {project.client.name}</span><h1>{project.title}</h1><p className="lead">{project.description ?? "Project delivery workspace"}</p><div className="progress large"><span style={{ width: `${progress}%` }}/></div><span className="muted">{progress}% complete · {completed}/{project.tasks.length} tasks</span></section>
    <TaskBoard projectId={project.id} initialTasks={project.tasks.map(({id,title,description,status})=>({id,title,description,status}))}/>
    <section className="detail-grid"><div className="card"><div className="section-title">Milestones</div>{project.milestones.map(item=><div className="compact-row" key={item.id}><b>{item.title}</b><span className="badge">{item.status}</span></div>)}<form className="inline-form" action={createMilestone}><input type="hidden" name="projectId" value={project.id}/><input name="title" required maxLength={160} placeholder="New milestone"/><button className="button">Add</button></form></div>
      <div className="card"><div className="section-title">Waiting for client</div>{project.clientActions.filter(item=>item.status === "OPEN").map(item=><div className="compact-row stack" key={item.id}><b>{item.title}</b>{item.description && <span className="muted">{item.description}</span>}</div>)}<form className="stack-form" action={createClientAction}><input type="hidden" name="projectId" value={project.id}/><input name="title" required maxLength={180} placeholder="Action title"/><textarea name="description" maxLength={2000} placeholder="What does the client need to do?"/><button className="button">Request action</button></form></div>
      <div className="card"><div className="section-title">Comments and notes</div>{project.comments.map(comment=><div className="message" key={comment.id}><div className="row"><b>{comment.authorName}</b><span className="muted">{comment.visibleToClient ? "Client visible" : "Internal"}</span></div><p>{comment.body}</p></div>)}<form className="stack-form" action={createComment}><input type="hidden" name="projectId" value={project.id}/><textarea name="body" required maxLength={5000} placeholder="Add a project note"/><label className="check"><input type="checkbox" name="visibleToClient" defaultChecked/> Visible to client</label><button className="button">Add comment</button></form></div>
      <div className="card"><div className="section-title">Files</div>{project.attachments.length ? project.attachments.map(file=><div className="compact-row" key={file.id}><div><a className="file-link" href={`/api/files/${file.id}`}><b>{file.fileName}</b></a><div className="muted small">{(file.sizeBytes / 1024).toFixed(1)} KB · {file.mimeType}</div></div><span className="badge">v{file.version}</span></div>) : <p className="empty">No files added yet.</p>}<details className="file-add"><summary>Add a local file</summary><form className="stack-form" action={uploadProjectFile}><input type="hidden" name="projectId" value={project.id}/><input type="file" name="file" required/><label className="check"><input type="checkbox" name="visibleToClient" defaultChecked/> Visible to client</label><button className="button">Upload file</button></form></details><details className="file-add"><summary>Download from URL</summary><form className="stack-form" action={importProjectFileFromUrl}><input type="hidden" name="projectId" value={project.id}/><input type="url" name="sourceUrl" required placeholder="https://example.com/file.pdf"/><label className="check"><input type="checkbox" name="visibleToClient" defaultChecked/> Visible to client</label><button className="button">Download and save</button></form></details><div className="section-title spaced">Activity</div><ul className="activity">{project.events.map(event=><li key={event.id}><b>{event.message}</b><br/><span className="muted">{event.createdAt.toLocaleString()}</span></li>)}</ul></div></section>
    <section className="detail-grid"><div className="card"><div className="section-title">Project templates</div><form className="inline-form" action={applyProjectTemplate}><input type="hidden" name="projectId" value={project.id}/><select name="templateId" required defaultValue=""><option value="" disabled>Select template</option>{templates.map(template=><option value={template.id} key={template.id}>{template.name}</option>)}</select><button className="button">Apply</button></form><p className="muted small">Template tasks are appended without replacing the imported Services scope.</p></div><div className="card"><div className="section-title">Change requests</div>{project.changeRequests.length ? project.changeRequests.map(request=><article className="change-request" key={request.id}><div className="row"><b>{request.title}</b><span className="badge">{request.status}</span></div><p>{request.description}</p><span className="muted">Requested by {request.requestedBy}</span><form className="stack-form" action={reviewChangeRequest}><input type="hidden" name="projectId" value={project.id}/><input type="hidden" name="requestId" value={request.id}/><select name="status" defaultValue={request.status}><option value="REVIEWING">Reviewing</option><option value="QUOTED">Quoted</option><option value="APPROVED">Approved</option><option value="DECLINED">Declined</option><option value="COMPLETED">Completed</option></select><div className="form-columns"><input name="amount" type="number" min="0" step="0.01" placeholder="Estimated amount" defaultValue={request.estimatedAmount?.toString()}/><input name="days" type="number" min="1" placeholder="Estimated days" defaultValue={request.estimatedDays ?? ""}/></div><textarea name="response" maxLength={3000} placeholder="Response to client" defaultValue={request.adminResponse ?? ""}/><button className="button">Save review</button></form></article>) : <p className="empty">No change requests.</p>}</div></section>
  </main>;
}
